-- 1) Create a Supabase project.
-- 2) Run this SQL in Supabase SQL Editor.
-- 3) In Authentication > Users, create the admin user with email/password.
-- 4) Copy that user's UUID and run the final INSERT below.

create table if not exists public.admins (
  id uuid primary key references auth.users(id) on delete cascade
);

create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  title text not null,
  country text,
  specialty text,
  quantity text,
  salary text,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  job text not null,
  governorate text,
  qualification text,
  experience text,
  cv_url text,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.labor_requests (
  id bigint generated by default as identity primary key,
  company_name text not null,
  contact_name text not null,
  country text,
  phone text not null,
  job_title text not null,
  quantity text,
  requirements text,
  benefits text,
  notes text,
  created_at timestamptz not null default now()
);

alter table public.admins enable row level security;
alter table public.jobs enable row level security;
alter table public.applications enable row level security;
alter table public.labor_requests enable row level security;

-- Public visitors can only read active jobs.
create policy "public read active jobs" on public.jobs
for select using (is_active = true);

-- Admins can manage all jobs.
create policy "admins manage jobs" on public.jobs
for all to authenticated
using (exists (select 1 from public.admins a where a.id = auth.uid()))
with check (exists (select 1 from public.admins a where a.id = auth.uid()));

-- Anyone can submit applications and labor requests.
create policy "public insert applications" on public.applications
for insert to anon, authenticated with check (true);

create policy "public insert labor requests" on public.labor_requests
for insert to anon, authenticated with check (true);

-- Only admins can read submitted applications/requests.
create policy "admins read applications" on public.applications
for select to authenticated
using (exists (select 1 from public.admins a where a.id = auth.uid()));

create policy "admins read labor requests" on public.labor_requests
for select to authenticated
using (exists (select 1 from public.admins a where a.id = auth.uid()));

-- After creating the admin user in Authentication, replace USER_UUID below:
-- insert into public.admins (id) values ('USER_UUID');

-- Optional sample job:
-- insert into public.jobs (title,country,specialty,quantity,salary,description)
-- values ('مثال: طباخ', 'السعودية', 'مطاعم', '5', 'حسب الاتفاق', 'خبرة مناسبة في المجال');
